language: python

python:
  - "3.8"

before_install:
  - sudo dpkg --add-architecture i386
  - wget -nc https://dl.winehq.org/wine-builds/winehq.key
  - sudo apt-key add winehq.key
  - sudo apt-add-repository 'deb https://dl.winehq.org/wine-builds/ubuntu/ xenial main'
  - sudo apt-get update
  - sudo apt-get install --install-recommends winehq-stable

install: pip install tox-travis

script: tox

notifications:
  email:
    recipients:
      - lucasgrishioni@gmail.com
    on_sucess: always
    on_failure: always